# Generated by Django 3.2.4 on 2021-06-27 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('1', 'Residencial'), ('2', 'Comercial')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Los Edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProp', models.CharField(max_length=150)),
                ('costo', models.FloatField()),
                ('numCuartos', models.IntegerField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificio', to='administrativo.edificio')),
            ],
            options={
                'verbose_name_plural': 'Los Departamentos',
                'ordering': ['nombreProp'],
            },
        ),
    ]
